version: '2'

services:
  cyclid-server:
    build: cyclid_server
    expose:
      - "8361"
    ports:
      - "8361:8361"
    env_file: .env
    command: ["/wait-for-it.sh", "cyclid-db:3306", "-t", "30", "--", "/entrypoint.sh"]
    depends_on:
      - cyclid-db
      - cyclid-sidekiq
      - cyclid-redis
  cyclid-ui:
    build: cyclid_ui
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - cyclid-server
  cyclid-sidekiq:
    build: cyclid_sidekiq
    env_file: .env
    entrypoint: sidekiq -e production -L /var/log/sidekiq.log -r /var/lib/cyclid/sidekiq.rb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  cyclid-db:
    image: "mysql"
    env_file: .env
  cyclid-redis:
    image: "redis"
